spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://stats-db:5432/statsdb
    username: stats
    password: statspass
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/