-- Таблица взаимодействий пользователей
CREATE TABLE IF NOT EXISTS user_actions (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            user_id BIGINT NOT NULL,
                                            event_id BIGINT NOT NULL,
                                            weight DOUBLE PRECISION NOT NULL,
                                            action_type VARCHAR(20) NOT NULL,
    last_action_time TIMESTAMP NOT NULL,
    CONSTRAINT uq_user_event UNIQUE (user_id, event_id)
    );

-- Таблица сходства мероприятий
CREATE TABLE IF NOT EXISTS event_similarity (
                                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                event_a BIGINT NOT NULL,
                                                event_b BIGINT NOT NULL,
                                                score DOUBLE PRECISION NOT NULL,
                                                updated TIMESTAMP NOT NULL,
                                                CONSTRAINT uq_event_pair UNIQUE (event_a, event_b),
    CONSTRAINT chk_event_a_less_b CHECK (event_a < event_b)
    );

-- Индексы
CREATE INDEX IF NOT EXISTS idx_user_actions_user_id ON user_actions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_actions_event_id ON user_actions(event_id);
CREATE INDEX IF NOT EXISTS idx_user_actions_time ON user_actions(last_action_time DESC);
CREATE INDEX IF NOT EXISTS idx_event_similarity_event_a ON event_similarity(event_a);
CREATE INDEX IF NOT EXISTS idx_event_similarity_event_b ON event_similarity(event_b);
CREATE INDEX IF NOT EXISTS idx_event_similarity_score ON event_similarity(score DESC);