-- Создание баз данных для каждого сервиса
CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS eventdb;
CREATE DATABASE IF NOT EXISTS requestdb;
CREATE DATABASE IF NOT EXISTS commentdb;
CREATE DATABASE IF NOT EXISTS statsdb;

-- Создание пользователей
CREATE USER IF NOT EXISTS user WITH PASSWORD 'userpass';
CREATE USER IF NOT EXISTS event WITH PASSWORD 'eventpass';
CREATE USER IF NOT EXISTS request WITH PASSWORD 'requestpass';
CREATE USER IF NOT EXISTS comment WITH PASSWORD 'commentpass';
CREATE USER IF NOT EXISTS stats WITH PASSWORD 'statspass';

-- Права доступа
GRANT ALL PRIVILEGES ON DATABASE userdb TO user;
GRANT ALL PRIVILEGES ON DATABASE eventdb TO event;
GRANT ALL PRIVILEGES ON DATABASE requestdb TO request;
GRANT ALL PRIVILEGES ON DATABASE commentdb TO comment;
GRANT ALL PRIVILEGES ON DATABASE statsdb TO stats;