apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ewm.fullname" . }}-db-secret
  labels:
    {{- include "ewm.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ewm.fullname" . }}-redis-secret
  labels:
    {{- include "ewm.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.redis.auth.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ewm.fullname" . }}-jwt-secret
  labels:
    {{- include "ewm.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.env.JWT_SECRET | b64enc | quote }}
---
  {{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "ewm.fullname" . }}-aws-secrets
  labels:
    {{- include "ewm.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ include "ewm.fullname" . }}-aws-secrets
  data:
      - secretKey: db-password
        remoteRef:
          key: {{ .Values.externalSecrets.dbKey }}
          property: password
        - secretKey: redis-password
          remoteRef:
            key: {{ .Values.externalSecrets.redisKey }}
            property: password
        - secretKey: jwt-secret
          remoteRef:
            key: {{ .Values.externalSecrets.jwtKey }}
            property: secret
  {{- end }}