apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
stringData:
  username: admin
  passphrase: admin
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  addonComponents:
    kiali:
      enabled: true
    prometheus:
      enabled: true
    grafana:
      enabled: true
    tracing:
      enabled: true
  values:
    kiali:
      enabled: true
      dashboard:
        secretName: kiali
      external_services:
        tracing:
          url: "http://tracing:16685"
        grafana:
          url: "http://grafana:3000"